version: "2"
services:
  database:
    ports:
     - "5432:5432"
    image: postgres
    environment:
      POSTGRES_USER: jdis
      POSTGRES_PASSWORD: compeIA

  migration:
    build: ./scripts/database/
    command: "bash ./wait.sh"
    depends_on:
      - database
    volumes:
      - "./scripts/database/:/usr/halite-backend/"

  web:
    ports:
      - "8080:8080"
    build: ./web/
    command: npm start
    volumes:
      - "./web:/usr/src"
      - "./bots:/usr/src/bots"
    depends_on:
      - migration

  runner:
    build: ./scripts/game_runner/
    command: python game_runner.py
    volumes:
      - "./web/public/:/usr/halite-backend/public/"
      - "./bots/:/usr/halite-backend/bots/"
    depends_on:
      - migration
