version: "2"
services:
  database:
    ports:
     - "5432:5432"
    image: postgres
    environment:
      POSTGRES_USER: jdis
      POSTGRES_PASSWORD: compeIA

  web:
    ports:
      - "8080:8080"
    build: ./web/
    command: npm start
    volumes:
      - "./web:/usr/src"

  runner:
    build: ./scripts/game_runner/
    command: python game_runner.py
    volumes:
      - "./web/public/:/usr/halite-backend/public/"
      - "./bots/:/usr/halite-backend/bots/"
